server:
  port: 7001
  
spring:
  application:
    name: jeecg-system
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
  config:
    import:
      - optional:classpath:config/application-liteflow.yml
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml
#  #shardingjdbc数据源
#  datasource:
#    dynamic:
#      datasource:
#        sharding-db:
#          driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#          url: jdbc:shardingsphere:nacos:sharding.yaml?serverAddr=@config.server-addr@&namespace=@config.namespace@&group=@config.group@