server:
  port: 5002
spring:
  data:
    redis:
      ##redis 单机环境配置
      host: localhost
      port: 6379
      database: 0
      password:
      ssl:
        enabled: false
  application:
    name: seata-account
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jeecg_account?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/schema-account.sql
seata:
  enable-auto-data-source-proxy: false
  service:
    grouplist:
      default: 127.0.0.1:8091
    vgroup-mapping:
      springboot-seata-group: default
  # seata 事务组编号 用于TC集群名
  tx-service-group: springboot-seata-group
  
# 无用配置，为了避免扫码全代码导致启动慢
minidao:
  base-package: org.jeecg.modules.jmreport.*